version: "3"
networks:
  mynetwork:
    driver: bridge
services:
  db:
    image: mysql:latest
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: passwordroot
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: nfts
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork
